// Define the structure for a project's detailed section
interface ProjectDetailSection {
  heading: string;
  content: string[]; // Using an array allows for bullet points
}

// Update the main Project interface
export interface Project {
  id: number;
  title: string;
  description: string;
  imageUrl: string;
  skills: string[];
  details: ProjectDetailSection[]; // Add the new details property
}

// Your list of projects with detailed content
export const projects: Project[] = [
  {
    id: 1,
    title: "Quadruped Robot Design & Control",
    description: "Designed a four-legged robot in CAD, focusing on balance and load handling. Currently building and testing a prototype leg with 3D-printed parts and developing Python-based control algorithms.",
    imageUrl: "/robot.png",
    skills: ["CAD", "3D Printing", "Prototyping", "Python", "Raspberry Pi"],
    details: [
      {
        heading: "Project Summary",
        content: [
          "Designed and modeled a four-legged robot in CAD, focusing on balance, load handling, and organic geometry.",
          "Currently building and testing the first prototype leg using 3D-printed joints and motor integration.",
          "Will next develop control algorithms for gait simulation and optimization using Raspberry Pi and Python."
        ]
      },
      {
        heading: "Affiliation",
        content: ["Columbia University, Hod Lipson Robotics Laboratory"]
      }
    ]
  },
  {
    id: 2,
    title: "Optimization of Heat Recovery from a Computer",
    description: "Built a small-scale data center model using an oil-immersed CPU to recover waste heat. Designed and optimized a dual-circuit system, achieving 81% heat recovery efficiency.",
    imageUrl: "/heat_conservation.png",
    skills: ["Heat Transfer", "System Design", "Simulation", "Calorimetry", "Thermodynamics"],
    details: [
      {
        heading: "My Contribution",
        content: [
          "Built a small-scale data center model using an oil-immersed CPU.",
          "Tested oil's dielectric strength and thermal capacity for heat recovery.",
          "Designed and optimized a dual-circuit system for efficient heat transfer.",
          "Ran simulations to replicate data center CPU loads and analyze performance.",
          "Analyzed efficiency and losses using calorimetry and thermal resistance calculations."
        ]
      },
      {
        heading: "Key Results",
        content: [
          "Achieved 81% efficiency in heat recovery under experimental conditions.",
          "Calculated a potential for 95% efficiency at an industrial scale."
        ]
      },
      {
        heading: "Concept Overview",
        content: [
          "The project addresses the waste of heat generated by CPUs by recovering it to warm water for urban use. A motherboard immersed in vegetable oil (an electrical insulator and heat transfer medium) simulates a data center, allowing for safe and efficient heat capture."
        ]
      }
    ]
    }
];